CREATE DATABASE Nyous;

USE Nyous;

CREATE TABLE Acesso(
	IdAcesso INT IDENTITY PRIMARY KEY NOT NULL,
	Tipo VARCHAR(50) NOT NULL
);

CREATE TABLE Categoria(
	IdCategoria INT IDENTITY PRIMARY KEY NOT NULL,
	Titulo VARCHAR(50) NOT NULL
);

CREATE TABLE Localizacao(
	IdLocalizacao INT IDENTITY PRIMARY KEY NOT NULL,
	Logradouro VARCHAR(100) NOT NULL,
	Numero VARCHAR(50) NOT NULL,
	Complemento VARCHAR(50),
	Bairro VARCHAR(50) NOT NULL,
	Cidade VARCHAR(50) NOT NULL,
	UF VARCHAR(2) NOT NULL,
	CEP VARCHAR(10) NOT NULL,
);

CREATE TABLE Usuario(
	IdUsuario INT IDENTITY PRIMARY KEY NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(80) NOT NULL,
	Senha VARCHAR(100) NOT NULL,
	DataNascimento DATETIME,

	IdAcesso INT FOREIGN KEY REFERENCES Acesso(IdAcesso)
);

CREATE TABLE Evento(
	IdEvento INT IDENTITY PRIMARY KEY NOT NULL, 
	DataEvento DATETIME NOT NULL,
	AcessoRestrito BINARY DEFAULT 0,
	Capacidade INT NOT NULL,
	Descricao VARCHAR(255),

	IdLocalizacao INT FOREIGN KEY REFERENCES Localizacao(IdLocalizacao),
	IdCategoria INT FOREIGN KEY REFERENCES Categoria(IdCategoria)
);

CREATE TABLE Convite(
	IdConvite INT IDENTITY PRIMARY KEY NOT NULL,
	Confirmado BIT DEFAULT NULL,

	IdEvento INT FOREIGN KEY REFERENCES Evento(IdEvento),
	IdUsuarioEmissor INT FOREIGN KEY REFERENCES Usuario(IdUsuario),
	IdUsuarioConvidado INT FOREIGN KEY REFERENCES Usuario(IdUsuario),
);

CREATE TABLE Presenca(
	IdPresenca INT IDENTITY PRIMARY KEY NOT NULL,
	Confirmado BIT DEFAULT NULL,

	IdEvento INT FOREIGN KEY REFERENCES Evento(IdEvento),
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario)
);